# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33dadeb15fb052c310f86042c3fe4391965297b4c1077209b9b8c87c481e6a6870a6ba42dac06124cbe05da042688100f03e4accec449e4d8ab5be90c55afb11

test:
  secret_key_base: ce931889a1c556a15da08af6fe583e4ea22108565f8488fc67ef9e2a7393953a4ed2c0617091c874fdf70fed864827acd639f9de5210c5daf7277bd9334de7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
